import { 
  Check, 
  X,
  Circle,
  Bell,
  Settings,
  LogOut,
  Search,
  Swords,
  User2,
  Users,
  UserPlus,
  MailPlus,
  Camera,
  Trash,
  MoreHorizontal,
  FileEdit,
  Layers,
  GraduationCap
} from "lucide-react"
export const Icons = {
  x: X,
  circle: Circle,
  check: Check,
  bell: Bell,
  settings: Settings,
  logout: LogOut,
  search: Search,
  sword: Swords,
  user: User2,
  users: Users,
  userPlus: UserPlus,
  mailPlus: MailPlus,
  camera: Camera,
  trash: Trash,
  moreHorizontal: MoreHorizontal,
  fileEdit: FileEdit,
  layers: Layers,
  graduationCap: GraduationCap,
}